'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuthStore } from '@/store/authStore';
import { recommendationService } from '@/services/api';
import { Bookmark, ShoppingBag, ExternalLink, Loader2, Trash2 } from 'lucide-react';

export default function SavedLooks() {
  const router = useRouter();
  const { savedLooks, setSavedLooks, token, initializeAuth } = useAuthStore();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    initializeAuth();
    if (!token) {
      router.push('/login?redirect=/saved');
      return;
    }

    const fetchSavedLooks = async () => {
      try {
        const data = await recommendationService.getSavedLooks();
        setSavedLooks(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchSavedLooks();
  }, [token, router, setSavedLooks]);

  const handleUnsave = async (lookId) => {
    try {
      await recommendationService.unsaveLook(lookId);
      setSavedLooks(savedLooks.filter(item => item.look.id !== lookId));
    } catch (err) {
      console.error(err);
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center py-24">
        <Loader2 className="h-8 w-8 animate-spin text-indigo-400" />
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8">
      <div className="flex items-center space-x-3 mb-8">
        <div className="rounded-xl bg-indigo-500/10 p-2.5 text-indigo-400">
          <Bookmark className="h-6 w-6 fill-current" />
        </div>
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight text-white">Saved Looks</h1>
          <p className="text-sm text-slate-400">Your styled outfits generated by the AI matching system.</p>
        </div>
      </div>

      {savedLooks.length === 0 ? (
        <div className="glass-panel p-12 rounded-2xl text-center flex flex-col items-center justify-center">
          <ShoppingBag className="h-12 w-12 text-slate-650 mb-4" />
          <h3 className="text-lg font-bold text-white mb-1">No saved outfits yet</h3>
          <p className="text-sm text-slate-500 max-w-sm mb-6">
            Generate looks with the styling tool, choose the combinations you love, and bookmark them here.
          </p>
          <button 
            onClick={() => router.push('/generator')}
            className="px-5 py-2.5 rounded-xl bg-indigo-650 text-white hover:bg-indigo-700 font-bold text-sm shadow-md transition-all animate-pulse"
          >
            Generate Outfit
          </button>
        </div>
      ) : (
        <div className="space-y-10">
          {savedLooks.map((saved) => {
            const look = saved.look;
            return (
              <div key={saved.id} className="glass-panel p-6 rounded-2xl border border-white/5 space-y-6 animate-fade-in">
                {/* Header */}
                <div className="flex flex-col sm:flex-row justify-between items-start gap-4 pb-4 border-b border-white/5">
                  <div>
                    <h3 className="text-xl font-bold text-white">{look.lookName}</h3>
                    <p className="text-sm text-slate-450 italic mt-1">&ldquo;{look.stylingNotes}&rdquo;</p>
                  </div>
                  
                  <button
                    onClick={() => handleUnsave(look.id)}
                    className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg border border-rose-500/20 text-rose-400 hover:text-white hover:bg-rose-550 text-xs font-semibold tracking-wide transition-all"
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                    <span>Delete Look</span>
                  </button>
                </div>

                {/* Items grid */}
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
                  {look.items.map((item) => {
                    const product = item.matchedProduct;
                    return (
                      <div key={item.id} className="glass-card p-4 rounded-xl border border-white/5 flex flex-col justify-between h-56">
                        <div>
                          <span className="inline-flex items-center rounded-md bg-indigo-500/10 px-2 py-0.5 text-[10px] font-bold text-indigo-400 mb-2">
                            {item.category}
                          </span>
                          <h4 className="text-xs font-bold text-white line-clamp-2">{item.description}</h4>
                        </div>

                        {product ? (
                          <div className="border-t border-white/5 pt-3 mt-3 flex items-center justify-between">
                            <div>
                              <span className="text-[10px] text-slate-500 block">Price</span>
                              <span className="text-xs font-extrabold text-white">₹{product.price}</span>
                            </div>
                            <a
                              href={product.productUrl}
                              target="_blank"
                              rel="noopener noreferrer"
                              className="p-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-350 hover:text-white transition-all border border-white/5"
                              title={`Buy on ${product.marketplace}`}
                            >
                              <ExternalLink className="h-3.5 w-3.5" />
                            </a>
                          </div>
                        ) : (
                          <div className="text-[10px] text-slate-500 italic mt-3 pt-3 border-t border-white/5">
                            No active store item match.
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
